"use client"

import React from 'react';
import { Dancing_Script, Inter } from 'next/font/google';
import './styles/globals.css';
import { FlowerizeProvider } from './provider/FlowerizeProvider';
import { Head } from 'next/head';

// Use client directive at the module scope

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Flowerize',
//   description: 'Generated by create next app',
// }

export const dancingScript = Dancing_Script({ weight: "700", subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`{${inter.className} bg-gradient-to-b from-slate-50 to-rose-200 h-screen`}>
        <main className=' flex justify-center items-center mx-4'>
          <FlowerizeProvider>
            {children}
          </FlowerizeProvider>
        </main>
      </body>
    </html>
  );
}
